/*****************************************************************************

						ATENTION
						
   DO NOT EDIT THIS FILE. 
   THIS FILE IS AUTOMATIC GENERATED BY MARIAMOLE
   ALL CHANGES IN THIS FILE WILL BE LOST

*****************************************************************************/

//---------------------------------------------------------------------------
#ifndef _MARIAMOLE_AUTOMATIC_CODE_H
#define _MARIAMOLE_AUTOMATIC_CODE_H
//---------------------------------------------------------------------------

#include <Arduino.h>

/*--MARIMOLE-DEF_BEGIN--*/
/*--MARIMOLE-DEF_END--*/

#endif